---
Name: silverstripe-gutenberg-editor
---

# Configure Admin Extensions:

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - "mademedia/silverstripe-gutenberg-editor: admin/client/dist/styles/bundle.css"
  extra_requirements_javascript:
    - "mademedia/silverstripe-gutenberg-editor: admin/client/dist/js/bundle.js"
