---
Name: silverstripegutenberg
After:
  - '#corefieldtypes'
---

SilverStripe\Core\Injector\Injector:
  GutenbergText:
    class: MadeHQ\Gutenberg\FieldTypes\DBGutenbergText
  MadeHQ\Gutenberg\Controllers\APIController:
    properties:
      ThumbnailGenerator: '%$SilverStripe\AssetAdmin\Model\ThumbnailGenerator.assetadmin'
