---
Name: silverstripegutenberg
After:
  - '#corefieldtypes'
---

# Configure Admin Extensions:

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - "mademedia/silverstripe-gutenberg-editor: client/dist/style.css"
  extra_requirements_javascript:
    - "mademedia/silverstripe-gutenberg-editor: client/dist/globals.js"
    - "mademedia/silverstripe-gutenberg-editor: client/dist/bundle.js"

SilverStripe\Core\Injector\Injector:
  GutenbergText:
    class: MadeHQ\Gutenberg\FieldTypes\DBGutenbergText
